### ISSUE TITLE
Fast API Design Pattern

### ISSUE THREAD

**Issue by tjsgh531** [tjsgh531/get-me-a-job#2]
## DESCRIPTION

기본적인 FastAPI 디렉토리 구조와 기본 코드를 작성해보자!

## TASKS

- [x] install library 정리
- [ ] main.py 작성
- [ ] database.py 작성
- [ ] models.py 작성
- [ ] crud.oy 작성
- [ ] schemas.py 작성
- [ ] router.py 작성

## REFERS

- [wikidocs fastapi]("https://wikidocs.net/book/8531")
